MATCHMAKING_QUEUES = {
    0: "Custom game",
    72: "Howling Abyss	1v1 Snowdown Showdown games",
    73: "Howling Abyss	2v2 Snowdown Showdown games",
    75: "Summoner's Rift	6v6 Hexakill games",
    76: "Summoner's Rift	Ultra Rapid Fire games",
    78: "Howling Abyss	One For All: Mirror Mode games",
    83: "Summoner's Rift	Co-op vs AI Ultra Rapid Fire games",
    98: "Twisted Treeline	6v6 Hexakill games",
    100: "Butcher's Bridge	5v5 ARAM games",
    310: "Summoner's Rift	Nemesis games",
    313: "Summoner's Rift	Black Market Brawlers games",
    317: "Crystal Scar	Definitely Not Dominion games",
    325: "Summoner's Rift	All Random games",
    400: "Summoner's Rift	5v5 Draft Pick games",
    420: "Summoner's Rift	5v5 Ranked Solo games",
    430: "Summoner's Rift	5v5 Blind Pick games",
    440: "Summoner's Rift	5v5 Ranked Flex games",
    450: "Howling Abyss	5v5 ARAM games",
    460: "Twisted Treeline	3v3 Blind Pick games",
    470: "Twisted Treeline	3v3 Ranked Flex games",
    600: "Summoner's Rift	Blood Hunt Assassin games",
    610: "Cosmic Ruins	Dark Star: Singularity games",
    700: "Summoner's Rift	Clash games",
    800: "Twisted Treeline	Co-op vs. AI Intermediate Bot games",
    810: "Twisted Treeline	Co-op vs. AI Intro Bot games",
    820: "Twisted Treeline	Co-op vs. AI Beginner Bot games",
    830: "Summoner's Rift	Co-op vs. AI Intro Bot games",
    840: "Summoner's Rift	Co-op vs. AI Beginner Bot games",
    850: "Summoner's Rift	Co-op vs. AI Intermediate Bot games",
    900: "Summoner's Rift	ARURF games",
    910: "Crystal Scar	Ascension games",
    920: "Howling Abyss	Legend of the Poro King games",
    940: "Summoner's Rift	Nexus Siege games",
    950: "Summoner's Rift	Doom Bots Voting games",
    960: "Summoner's Rift	Doom Bots Standard games",
    980: "Valoran City Park	Star Guardian Invasion: Normal games",
    990: "Valoran City Park	Star Guardian Invasion: Onslaught games",
    1000: "Overcharge	PROJECT: Hunters games",
    1010: "Summoner's Rift	Snow ARURF games",
    1020: "Summoner's Rift	One for All games",
    1030: "Crash Site	Odyssey Extraction: Intro games",
    1040: "Crash Site	Odyssey Extraction: Cadet games",
    1050: "Crash Site	Odyssey Extraction: Crewmember games",
    1060: "Crash Site	Odyssey Extraction: Captain games",
    1070: "Crash Site	Odyssey Extraction: Onslaught games",
    1200: "Nexus Blitz	Nexus Blitz game",
}
